### ISSUE TITLE
Chatlogs crashing the server

### ISSUE THREAD

**Issue by Spearritt** [DataSynchronized/SyncAdmin#13]
This is rare, but when it happens, it says "Script error. Player must be a child of players." and then crashes the server, or disconnects a large portion of the players in the server.

http://prntscr.com/gau15y

**Comment by DataSynchronized** [comment]
Hey @Spearritt 

Thank you for reporting this issue. Could you tell us the command you was running for this issue to occur?
Please note that we cannot help if the plugin was a customly made plugin which is not officially endorsed by SyncAdmin.

Thanks!

**Comment by Spearritt** [comment]
It was just :chatlogs

The plugin hasn't been modified, the server was aprox. running for 20 hours.

**Comment by Spearritt** [comment]
https://gyazo.com/0b35842af6924ac22435f979f571582a

When I tried to run ":settings"

**Comment by YouFoundSci** [comment]
Yep. Got the same issue recently.

**Comment by DataSynchronized** [comment]
We're still reviewing this bug but cannot seem to reproduce this issue on our end.

If you can find a way to repro this issue, please let us know.

**Comment by Spearritt** [comment]
This seems to of been fixed with a recent update.
