### ISSUE TITLE
Entire chatlogs wont display

### ISSUE THREAD

**Issue by YouFoundSci** [DataSynchronized/SyncAdmin#23]
I recently encountered an issue where when I would chatlog search a certain user, they're entire chatlogs won't display.  I know this because I checked the person's chatlogs before, and it showed everything, but when I checked it again, it cut off half of their chatlogs. Please fix this issue, as it is going to be hard to interview people at Soro's if the chatlogs are broken. (I will supply an image of both chatlogs later today, after interviews.)

**Comment by Spearritt** [comment]
Hi,

After 500 chats, old chats are cleared to avoid memory being filled.

**Comment by stillunt1tled** [comment]
@Spearritt (or @DataSynchronized) Please close this issue
