### ISSUE TITLE
Slock doesn't detect lvl1+ users.

### ISSUE THREAD

**Issue by Railworks2** [DataSynchronized/SyncAdmin#3]
[19:22] aclectics || haseeb: ok so all i know is
[19:23] aclectics || haseeb: when i join the game i have mod and can't get past slock
[19:23] aclectics || haseeb: only in the training centre

**Comment by DataSynchronized** [comment]
Hey there,

Thank you for reporting this issue. Could you have the user who is experiencing this issue attach the plugin .lua file on this issue report please.

Thank you.

**Comment by Railworks2** [comment]
@DataSynchronized You'll need to talk to Sam, since he owns the IB. (Soro's)

**Comment by DataSynchronized** [comment]
Could you ask him to add the file here then.

Thanks!

**Comment by Railworks2** [comment]
Sam has failed to respond to the request, even after an extended period of time.

**Comment by DataSynchronized** [comment]
I would make sure your plugin is updated with the latest version found here: https://github.com/DataSynchronized/SyncAdmin/blob/master/Default%20Plugins/Administration/ServerLock.lua

If the problem still continues, feel free to post back here. @Railworks2

**Comment by Spearritt** [comment]
oh shutup rail

**Comment by Railworks2** [comment]
SMFH

**Comment by DataSynchronized** [comment]
Hey there,

This issue is being closed as we recommend that you keep all your plugins updated to the latest releases found here. If the problem occurs again, please open a new issue.

Thank you.
