### ISSUE TITLE
Root command references unused commands

### ISSUE THREAD

**Issue by Railworks2** [DataSynchronized/SyncAdmin#4]
![image](https://user-images.githubusercontent.com/27024242/28529359-3c89a0b2-7088-11e7-8490-ddfae102c5db.png)
In the most recent version of SyncAdmin, the root command has not been updated to reflect new SyncAdmin policies. The issue was privately stated within the internal system but not been dealt with.

The new phase should look similar to the following:

> Gives the SyncAdmin staff member an elevated, but heavily restricted and monitored permission level.
The ROOT permission can be restricted in your game by using the DMZ settings.

**Comment by DataSynchronized** [comment]
Hey there,

Thank you for reporting this issue to us. We will go ahead and release a fix for this issue.

Thanks!
