### ISSUE TITLE
":verify" command having a suspicious behavoir

### ISSUE THREAD

**Issue by Symplyfyed** [DataSynchronized/SyncAdmin#5]
Hi,

Recently I had a few issues with the SyncAdmin "**:verify**" command.
In some games it won't let me run it saying "You aren't SyncAdmin Staff".

I attached a few images for more info.
I'm not sure if this is a bug, or the contractors no longer have an uniform. I'd like to know what cause it.

Sincerely,
Symplyfyed.
![img_20170731_000440_376](https://user-images.githubusercontent.com/30578614/28757156-b2abfdec-7585-11e7-81fe-f5ca685fcb16.JPG)
![img_20170731_000414_718](https://user-images.githubusercontent.com/30578614/28757161-b9441216-7585-11e7-8004-4cf3e2574b6d.JPG)
![img_20170731_000342_385](https://user-images.githubusercontent.com/30578614/28757163-bcb5c318-7585-11e7-80ae-be07090aa74f.JPG)

**Comment by DataSynchronized** [comment]
Thank you for reporting this bug to us @Symplyfyed 
If you could give us a repro of how this bug occurs, that would be much appreciated.

Thank you!

**Comment by Spearritt** [comment]
Hello,

I'll investigate this further tonight.

Thank you for reporting this issue.

**Comment by Symplyfyed** [comment]
Thank you @Spearritt 

@DataSynchronized 
I have a suspicion about how may be possible as the game in which the command didn't work, use an outdated loader and / or the loader wasn't updated. I see that there are missing features.
![img_20170731_002421_651](https://user-images.githubusercontent.com/30578614/28757255-3e5af7ca-7587-11e7-9620-7baaa747dd10.JPG)

However I saw this happening recently but I'm not remember in which game, 

Below I attached a image that may help.
It shows the last changelog, and also I don't see the gameinfo command to be available.
![img_20170731_002421_651](https://user-images.githubusercontent.com/30578614/28757275-7eddd506-7587-11e7-8f8e-2a2994a57feb.JPG)

**Comment by Spearritt** [comment]
Can you send us the gameID.

Regards,
Sam

**Comment by Symplyfyed** [comment]
@Spearritt 

There: https://www.roblox.com/games/614070100/

**Comment by DataSynchronized** [comment]
Hey there @Symplyfyed 

The update to the verified command only applies to new versions of SyncAdmin. The game linked above is outdated and should be updated to the latest release.

Thank you.
